- name: Copy node_exporter binary file
  copy:
    src: ../files/node_exporter
    dest: "{{ NODE_EXPORTER.DEST }}/node_exporter"
    owner: root
    group: root
    mode: 0755
  become: true

- name: Copy systemd file
  template:
    src: ../files/node_exporter.service.j2
    dest: /etc/systemd/system/node_exporter.service
    owner: root
    group: root
    mode: 0644
  notify: require_node_exporter_restart
  become: true

- name: Enabled and start node_exporter service
  systemd:
    name: node_exporter.service
    enabled: yes
    state: started
    daemon_reload: yes
  become: true
