- name: Check CPU architecture
  shell: uname -m
  register: cpu_architecture
  changed_when: false

- name: Copy node_exporter binary file for raspi4
  copy:
    src: ../files/node_exporter-arm64
    dest: "{{ NODE_EXPORTER.DEST }}/node_exporter"
    owner: root
    group: root
    mode: 0755
  become: true
  notify: require_node_exporter_restart
  when: cpu_architecture.stdout == 'aarch64'

- name: Copy node_exporter binary file for raspi zero
  copy:
    src: ../files/node_exporter-armv6
    dest: "{{ NODE_EXPORTER.DEST }}/node_exporter"
    owner: root
    group: root
    mode: 0755
  become: true
  notify: require_node_exporter_restart
  when: cpu_architecture.stdout == 'armv6l'

- name: Copy systemd file
  template:
    src: ../templates/node_exporter.service.j2
    dest: /lib/systemd/system/node_exporter.service
    owner: root
    group: root
    mode: 0644
  notify: require_node_exporter_restart
  become: true

- name: Enabled and start node_exporter service
  systemd:
    name: node_exporter.service
    enabled: yes
    state: started
    daemon_reload: yes
  become: true
