---
- name: Deploy flannel to k8s
  shell: kubectl apply -f https://raw.githubusercontent.com/coreos/flannel/master/Documentation/kube-flannel.yml

- name: Wait for Node Ready
  shell: kubectl get node --no-headers | awk '{print $2}'
  register: node_state
  until: node_state.stdout == "Ready"
  # Re-execute(60 x 5 seconds) until Ready,
  # and then proceed to the next task.
  retries: 60
  delay: 5
  changed_when: false
