---
- name: Copy kubeadm-config.yaml
  template:
    src: ../templates/kubeadm-config.yaml.j2
    dest: /opt/kubeadm-config.yaml
    owner: "{{ K8S.CONFIG.OWNER }}"
    group: "{{ K8S.CONFIG.GROUP }}"
    mode: 0644
  become: true

- name: Execute kubeadm init
  shell: kubeadm init --config /opt/kubeadm-config.yaml
  register: result_kubeadm_init
  become: true

- name: Display stdout of result (kubeadm init)
  debug:
    msg: "{{ result_kubeadm_init.stdout_lines }}"

- name: Create $HOME/.kube directory
  file:
    path: "/home/{{ K8S.CONFIG.OWNER }}/.kube/"
    state: directory
    owner: "{{ K8S.CONFIG.OWNER }}"
    group: "{{ K8S.CONFIG.GROUP }}"
    mode: 0755

- name: Copy k8s/admin.conf to $HOME/.kube/config
  copy:
    src: /etc/kubernetes/admin.conf
    remote_src: true
    dest: "/home/{{ K8S.CONFIG.OWNER }}/.kube/config"
    owner: "{{ K8S.CONFIG.OWNER }}"
    group: "{{ K8S.CONFIG.GROUP }}"
    mode: 0600
  become: yes
