---
- name: Execute kubeadm init
  shell: kubeadm init --pod-network-cidr=10.244.0.0/16
  become: true

- name: Create $HOME/.kube directory
  file:
    path: "/home/{{ K8S.CONFIG.OWNER }}/.kube/"
    state: directory
    owner: "{{ K8S.CONFIG.OWNER }}"
    group: "{{ K8S.CONFIG.GROUP }}"
    mode: 0755

- name: Copy k8s/admin.conf to $HOME/.kube/config
  copy:
    src: /etc/kubernetes/admin.conf
    remote_src: true
    dest: "/home/{{ K8S.CONFIG.OWNER }}/.kube/config"
    owner: "{{ K8S.CONFIG.OWNER }}"
    group: "{{ K8S.CONFIG.GROUP }}"
    mode: 0600
  become: yes
