---
- name: Copy cleanup shell
  template:
    src: ../templates/cleanup.j2
    dest: /home/{{ K8S.CONFIG.OWNER }}/cleanup.sh
    owner: "{{ K8S.CONFIG.OWNER }}"
    group: "{{ K8S.CONFIG.GROUP }}"
    mode: 0755

- name: Run cleanup shell (target raw device fresh)
  shell: /home/{{ K8S.CONFIG.OWNER }}/cleanup.sh
  become: yes

## todo wait

- name: Check lsblk -f
  shell: lsblk -f |grep {{ RAW_DEVICE_NAME }}
  register: result_disk_status
  failed_when: false
  changed_when: false

- name: Debug raw device; /dev/{{ RAW_DEVICE_NAME }} status
  debug:
    msg: Raw device checking..."{{ result_disk_status.stdout }}"
  changed_when: false
