---
- name: Install argocd
  community.kubernetes.k8s:
    state: present
    src: ../files/argocd.yaml

- name: Get admin password
  shell: kubectl -n argocd get secret argocd-initial-admin-secret -o jsonpath="{.data.password}" | base64 -d
  register: admin_password
  changed_when: no

- name: Get argocd server pod name
  shell: kubectl get pod -n argocd |grep argocd-server
  register: argocd_server_pod_name
  changed_when: no

- name: Setting argocd config
  shell: "xxxxxxxxxxxxxxx"

- name: Deployment argocd-app
  community.kubernetes.k8s:
    state: present
    src: ../files/argocd-app.yaml
