---
- name: Require node exporter restart
  systemd:
    name: node_exporter.service
    state: restarted
    daemon_reload: true
    enabled: true
  become: true
  listen: require_node_exporter_restart
