---
- name: Add fish shell apt repository
  apt_repository:
    repo: "ppa:fish-shell/release-3"
    state: present
    update_cache: yes
  become: yes

- name: Check fish version
  shell: fish --version
  register: check_fish_version
  failed_when: false
  changed_when: false

- name: Install fish shell packages
  apt:
    name: "{{ item }}"
    state: present
    update_cache: yes
  with_items:
    - fish
  become: yes
  # packageがない場合、または、upgradeフラグがTrueのときのみ、実行許可。
  when: >
    (check_fish_version.rc != 0) or
    (FISH.UPGRADE)

- name: Add fish config file
  copy:
    src: ../files/config.fish
    dest: ~/.config/fish/config.fish
    owner: "{{ FISH.CONFIG.OWNER }}"
    group: "{{ FISH.CONFIG.GROUP }}"
    mode: "{{ FISH.CONFIG.MODE }}"
  when: check_fish_version.rc != 0

- name: Change fish shell
  shell: chsh -s /usr/bin/fish
  become: yes
  when: check_fish_version.rc != 0
