---
- name: Add fish shell apt repository
  apt_repository:
    repo: "ppa:fish-shell/release-3"
    state: present
    update_cache: yes
  become: yes

- name: Check fish version
  shell: fish --version
  register: check_fish_version
  failed_when: false
  changed_when: false

- name: Install fish shell packages
  apt:
    name: fish
    state: present
    update_cache: yes
  become: yes
  when: >
    (check_fish_version.rc != 0) or
    (FISH.UPGRADE)

- name: Change user shell for fish
  user:
    name: "{{ FISH.CONFIG.OWNER }}"
    shell: /bin/fish
  become: yes

- name: Add fish config file
  copy:
    src: ../files/config.fish
    dest: "/home/{{ FISH.CONFIG.OWNER }}/.config/fish/config.fish"
    owner: "{{ FISH.CONFIG.OWNER }}"
    group: "{{ FISH.CONFIG.GROUP }}"
    mode: "{{ FISH.CONFIG.MODE }}"
