---
- name: Add fish shell apt repository
  apt_repository:
    repo: "ppa:fish-shell/release-3"
    state: present
    update_cache: yes
  become: true

# - name: Check fish version
#   shell: fish --version
#   register: check_fish_version
#   failed_when: false
#   changed_when: false
### allways verison up
- name: Install fish shell packages
  apt:
    name: fish
    state: present
    update_cache: yes
  become: true
  # when: >
  #   (check_fish_version.rc != 0) or
  #   (FISH.UPGRADE)

- name: Change user shell for fish
  user:
    name: "{{ FISH.CONFIG.OWNER }}"
    shell: /usr/bin/fish
  become: true

- name: Create directory /home/{{ FISH.CONFIG.OWNER }}/.config/fish
  file:
    path: "/home/{{ FISH.CONFIG.OWNER }}/.config/fish"
    state: directory
    owner: "{{ FISH.CONFIG.OWNER }}"
    group: "{{ FISH.CONFIG.GROUP }}"

- name: Add fish config file
  copy:
    src: ../files/config.fish
    dest: "/home/{{ FISH.CONFIG.OWNER }}/.config/fish/config.fish"
    owner: "{{ FISH.CONFIG.OWNER }}"
    group: "{{ FISH.CONFIG.GROUP }}"
    mode: "{{ FISH.CONFIG.MODE }}"

- name: Add fish variables file (color theme)
  copy:
    src: ../files/fish_variables
    dest: "/home/{{ FISH.CONFIG.OWNER }}/.config/fish/fish_variables"
    owner: "{{ FISH.CONFIG.OWNER }}"
    group: "{{ FISH.CONFIG.GROUP }}"
    mode: "{{ FISH.CONFIG.MODE }}"
