---
- name: Add docker GPG key
  apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    state: present
  become: yes

- name: Add docker apt repository
  apt_repository:
    repo: "deb [arch=arm64] https://download.docker.com/linux/ubuntu {{ ansible_distribution_release }} stable"
    state: present
    update_cache: yes
  become: yes

- name: Install Docker packages
  apt:
    name: "{{ item }}"
    state: present
    update_cache: yes
  with_items:
    - docker-ce
    - docker-ce-cli
    - containerd.io
  become: yes

- name: Hold k8s packages
  dpkg_selections:
    name: "{{ item }}"
    selection: hold
  with_items:
    - docker-ce
    - docker-ce-cli
    - containerd.io
  become: yes

- name: Add user to docker group
  user:
    name: "{{ UBUNTU.USER }}"
    groups: docker
    append: yes
  become: yes

- name: Ensure docker service is enabled
  systemd:
    name: docker
    state: started
    enabled: yes
  become: yes

- name: Systemd unmask docker.service
  systemd:
    name: docker.service
    masked: no
  become: yes

- name: Systemd unmask docker.socket
  systemd:
    name: docker.socket
    masked: no
  become: yes

- name: Check docker version
  shell: docker --version
  # register: check_docker_version
