---
- name: Require docker restart
  systemd:
    name: docker
    state: restarted
    daemon_reload: yes
    enabled: yes
  become: true
  listen: require_restart_docker

- name: Require kubelet restart
  systemd:
    name: kubelet
    state: restarted
    daemon_reload: yes
    enabled: yes
  become: true
  listen: require_restart_kubelet
