# https://zokibayashi.hatenablog.com/entry/2017/09/25/231055
# power management off
# No effect...

- name: Cron ping to gateway
  become: true
  cron:
    name: ping to gateway
    minute: "*/1"
    job: "ping -c 1 100.64.1.1; test $? -eq 1 && sudo ifconfig wlan0 up"
    state: present
  notify:
    - require_restart_cron
