# https://zokibayashi.hatenablog.com/entry/2017/09/25/231055
# power management off
# No effect...

- name: Cron reboot morning
  become: true
  cron:
    name: reboot morning
    minute: "0"
    hour: "4"
    job: "/sbin/reboot"
    state: present
  notify:
    - require_restart_cron
