# https://reference.wolfram.com/language/tutorial/I2CSetup.html.ja?source=footer
# https://stackoverflow.com/questions/42904712/i2c-not-detecting-issues-in-hardware-or-any-other
- name: Copy /boot/confis.txt file
  copy:
    src: "../files/boot_config.txt"
    dest: /boot/config.txt
    owner: root
    group: root
    mode: 0755
  become: true

- name: Copy /etc/modules file
  copy:
    src: "../files/modules"
    dest: /etc/modules
    owner: root
    group: root
    mode: 0644
  become: true

- name: Create directory {{ GPIO.SCRIPT.DEST }}
  file:
    path: "{{ GPIO.SCRIPT.DEST }}"
    state: directory
    owner: ubuntu
    group: ubuntu
    mode: 0755

- name: Copy irrp.py file
  copy:
    src: "../files/irrp.py"
    dest: "{{ GPIO.SCRIPT.DEST }}/irrp.py"
    owner: ubuntu
    group: ubuntu
    mode: 0755

- name: Copy codes.json file
  copy:
    src: "../files/codes.json"
    dest: "{{ GPIO.SCRIPT.DEST }}/codes.json"
    owner: ubuntu
    group: ubuntu
    mode: 0644

- name: Copy bme280i2c.py file
  copy:
    src: "../files/bme280i2c.py"
    dest: "{{ GPIO.SCRIPT.DEST }}/bme280i2c.py"
    owner: ubuntu
    group: ubuntu
    mode: 0755
