- name: Copy dhcpcd.conf
  template:
    src: "../templates/dhcpcd.conf.j2"
    dest: /etc/dhcpcd.conf
    owner: root
    group: netdev
    mode: 0664
  become: true

# https://reference.wolfram.com/language/tutorial/I2CSetup.html.ja?source=footer
# https://stackoverflow.com/questions/42904712/i2c-not-detecting-issues-in-hardware-or-any-other
- name: Copy /boot/confis.txt file
  copy:
    src: "../files/configs/boot_config.txt"
    dest: /boot/config.txt
    owner: root
    group: root
    mode: 0755
  become: true

- name: Copy /etc/modules file
  copy:
    src: "../files/configs/modules"
    dest: /etc/modules
    owner: root
    group: root
    mode: 0644
  become: true

- name: Copy pigpiod.service
  copy:
    src: "../files/configs/pigpiod.service"
    dest: /lib/systemd/system/pigpiod.service
    owner: root
    group: root
    mode: 0644
  become: true
  notify:
    - require_restart_pigpiod
