##### middleware #####
### nginx ###
- name: Copy nginx config file
  template:
    src: "../templates/nginx.conf.j2"
    dest: /etc/nginx/conf.d/nginx.conf
    owner: root
    group: root
    mode: 0644
  become: true
  notify:
    - require_restart_nginx

### uwsgi ###
- name: Create directory {{ UWSGI.ETC.DEST }}
  file:
    path: "{{ UWSGI.ETC.DEST }}"
    state: directory
    owner: root
    group: root
    mode: 0755
  become: true

- name: Create directory {{ UWSGI.LOG.DEST }}
  file:
    path: "{{ UWSGI.LOG.DEST }}"
    state: directory
    owner: root
    group: root
    mode: 0755
  become: true

- name: Create directory {{ UWSGI.OPT.DEST }}
  file:
    path: "{{ UWSGI.OPT.DEST }}"
    state: directory
    owner: root
    group: root
    mode: 0755
  become: true

- name: Copy uwsgi.ini file
  template:
    src: "../templates/uwsgi.ini.j2"
    dest: "{{ UWSGI.ETC.DEST }}/uwsgi.ini"
    owner: root
    group: root
    mode: 0644
  become: true
  notify:
    - require_restart_uwsgi

- name: Copy uwsgi.service file
  template:
    src: "../templates/uwsgi.service.j2"
    dest: "/lib/systemd/system/uwsgi.service"
    owner: root
    group: root
    mode: 0644
  become: true
  notify:
    - require_restart_uwsgi

### pigpiod ###
- name: Copy pigpiod.service
  copy:
    src: "../files/configs/pigpiod.service"
    dest: /lib/systemd/system/pigpiod.service
    owner: root
    group: root
    mode: 0644
  become: true
  notify:
    - require_restart_pigpiod
