- name: Install apt packages
  apt:
    # インストール済みならそのまま
    state: present
    name: "{{ item }}"
    update_cache: yes
  loop:
    - nginx
    - pigpio
    - i2c-tools
    - python3-dev
    - python3-pip
  notify:
    - require_restart_nginx
    - require_restart_pigpiod
  become: true

- name: Install python packages
  pip:
    executable: pip3
    # インストール済みならそのまま
    state: present
    name: "{{ item.name }}"
    # default(omit)は値が指定されてない場合、そのオプション自体を省略(記述なし)する
    version: "{{ item.version | default(omit) }}"
  loop:
    - { name: "uwsgi", version: "2.0.20" }
    - { name: "flask", version: "2.0.2" }
    - { name: "pigpio", version: "1.78" }
    - { name: "smbus", version: "1.1.post2" }
  become: true
