- name: Install pigpiod
  apt:
    name: "{{ item }}"
    state: present
    update_cache: yes
  loop:
    - pigpio
    - python3-pigpio
  notify: require_restart_pigpiod
  become: yes

- name: Enabled and start pigpiod service
  systemd:
    name: pigpiod.service
    enabled: yes
    state: started
    daemon_reload: yes
  become: true
