# https://reference.wolfram.com/language/tutorial/I2CSetup.html.ja?source=footer
# https://stackoverflow.com/questions/42904712/i2c-not-detecting-issues-in-hardware-or-any-other
- name: Copy /boot/config.txt file
  copy:
    src: "../files/configs/boot_config.txt"
    dest: /boot/config.txt
    owner: root
    group: root
    mode: 0755
  become: true

- name: Copy /etc/modules file
  copy:
    src: "../files/configs/modules"
    dest: /etc/modules
    owner: root
    group: root
    mode: 0644
  become: true

- name: Stop and disable services (view; systemctl list-units --type=service)
  service:
    name: "{{ item }}"
    state: stopped
    enabled: false
  loop:
    - "dphys-swapfile.service"
    - "keyboard-setup.service"
    - "triggerhappy.service"
    # - "plymouth.service"
  become: true
