apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argocd-app
  namespace: argocd
  annotations:
    argocd.argoproj.io/manifest-generate-paths: ..
    notifications.argoproj.io/subscribe.on-sync-succeeded.slack: argocd
    notifications.argoproj.io/subscribe.app-sync-failed.slack: argocd
    notifications.argoproj.io/subscribe.app-health-degraded.slack: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/mk10969/ouchi-k8s-cd
    targetRevision: HEAD
    path: argocd-app/prd
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
