# ---
# - name: netplan_apply
#   shell: netplan apply
#   become: yes
#   listen: require_netplan_apply

- name: sshd_restart
  systemd:
    name: sshd.service
    state: restarted
    daemon_reload: yes
  become: yes
  listen: require_sshd_restart
