---
- name: netplan_apply
  shell: netplan apply
  become: true
  listen: require_netplan_apply

- name: sshd_restart
  systemd:
    name: sshd.service
    state: restarted
    daemon_reload: yes
  become: true
  listen: require_sshd_restart
