---
- name: netplan_apply
  shell: netplan apply
  become: yes
  listen: required_netplan_apply

- name: sshd_restart
  systemd:
    name: sshd.service
    state: restarted
    daemon_reload: yes
  become: yes
  listen: required_sshd_restart
