---
- name: Add netplan file
  template:
    src: ../templates/99-config.j2
    dest: /etc/netplan/99-config.yaml
    owner: root
    group: root
    mode: 0644
  become: true
  notify: require_netplan_apply

- name: Add hosts file
  template:
    src: ../templates/hosts.j2
    dest: /etc/hosts
    owner: root
    group: root
    mode: 0644
  become: true

- name: Set hostname
  become: true
  hostname:
    name: "{{ inventory_hostname }}"

- name: Set timezone to Asia/Tokyo
  become: true
  timezone:
    name: Asia/Tokyo

- name: Add ssh config file
  copy:
    src: ../files/10-sshd.conf
    dest: /etc/ssh/sshd_config.d/10-sshd.conf
    owner: root
    group: root
    mode: 0644
  become: true
  notify: require_sshd_restart
