---
- name: Add hosts file
  template:
    src: ../templates/hosts.j2
    dest: /etc/hosts
    owner: root
    group: root
    mode: 0644
  become: true

- name: Set hostname
  become: true
  hostname:
    name: "{{ inventory_hostname }}"

- name: Set timezone to Asia/Tokyo
  become: true
  timezone:
    name: Asia/Tokyo

- name: Add ssh config file
  copy:
    src: ../files/10-sshd.conf
    dest: /etc/ssh/sshd_config.d/10-sshd.conf
    owner: root
    group: root
    mode: 0644
  become: true
  notify: require_sshd_restart

- name: Disable swap
  command: swapoff -a
  become: true
  when: ansible_swaptotal_mb > 0
