- name: Add netplan file (ethernet)
  template:
    src: ../templates/99-config.j2
    dest: /etc/netplan/99-config.yaml
    owner: root
    group: root
    mode: 0644
  become: true
  notify: require_netplan_apply
