- import_tasks: common.yaml

- import_tasks: ethernet.yaml
  when: inventory_hostname in groups["cluster"]

- import_tasks: wifi.yaml
  when: inventory_hostname in groups["edge"]

- import_tasks: zero-wifi.yaml
  when: inventory_hostname in groups["sensor"]
