---
- name: Copy arogcd manifest file
  copy:
    src: ../files/argocd.yaml
    dest: /opt/argocd.yaml
    owner: "{{ K8S.CONFIG.OWNER }}"
    group: "{{ K8S.CONFIG.GROUP }}"
    mode: "{{ K8S.CONFIG.MODE }}"
  become: yes

- name: Copy arogcd-app manifest file
  copy:
    src: ../files/argocd-app.yaml
    dest: /opt/argocd-app.yaml
    owner: "{{ K8S.CONFIG.OWNER }}"
    group: "{{ K8S.CONFIG.GROUP }}"
    mode: "{{ K8S.CONFIG.MODE }}"
  become: yes

- name: Install argocd
  shell: kubectl apply -f /opt/argocd.yaml

- name: Wait for argocd server running
  shell: kubectl get pod -n argocd |grep argocd-server | awk '{print $3}'
  register: argocd_server_state
  until: argocd_server_state.stdout == "Running"
  # Re-execute(60 x 10 seconds) until Ready,
  # and then proceed to the next task.
  retries: 60
  delay: 10
  changed_when: false

- name: Get arogcd admin password
  shell: kubectl -n argocd get secret argocd-initial-admin-secret -o jsonpath="{.data.password}" | base64 -d
  register: argocd_admin_password
  changed_when: false

- name: Get argocd server pod name
  shell: kubectl get pod -n argocd |grep argocd-server |awk '{print $1}'
  register: argocd_server_pod_name
  changed_when: false

- name: Setting argocd repository
  shell:
    cmd: |
      kubectl exec -i pod/{{ argocd_server_pod_name.stdout }} -n argocd -- bash <<'EOC'
      argocd login localhost:8080 --username admin --password {{ argocd_admin_password.stdout }} --insecure
      argocd repo add https://github.com/mk10969/ouchi-kubernetes --username mk10969 --password {{ lookup('env','GITHUB_ACCESS_TOKEN') }}
      EOC
  register: argocd_repository

- name: Deploy argocd-app
  shell: kubectl apply -f /opt/argocd-app.yaml
