---
- name: Copy arogcd manifest file
  copy:
    src: ../files/argocd.yaml
    dest: /home/{{ K8S.CONFIG.OWNER }}/argocd.yaml
    owner: "{{ K8S.CONFIG.OWNER }}"
    group: "{{ K8S.CONFIG.GROUP }}"
    mode: "{{ K8S.CONFIG.MODE }}"

- name: Copy arogcd-app manifest file
  copy:
    src: ../files/argocd-app.yaml
    dest: /home/{{ K8S.CONFIG.OWNER }}/argocd-app.yaml
    owner: "{{ K8S.CONFIG.OWNER }}"
    group: "{{ K8S.CONFIG.GROUP }}"
    mode: "{{ K8S.CONFIG.MODE }}"

- name: Install argocd
  shell: kubectl apply -f /home/{{ K8S.CONFIG.OWNER }}/argocd.yaml

### TODO
# - name: Wait (waiting for... argocd deploy ok)

- name: Get arogcd admin password
  shell: kubectl -n argocd get secret argocd-initial-admin-secret -o jsonpath="{.data.password}" | base64 -d
  register: argocd_admin_password
  changed_when: false

- name: Get argocd server pod name

  shell: kubectl get pod -n argocd |grep argocd-server |awk '{print $1}'
  register: argocd_server_pod_name
  changed_when: false

- name: Setting argocd repository
  shell:
    cmd: |
      kubectl exec -i pod/{{ argocd_server_pod_name.stdout }} -n argocd -- bash <<'EOC'
      argocd login localhost:8080 --username admin --password {{ argocd_admin_password.stdout }} --insecure
      argocd repo add https://github.com/mk10969/ouchi-kubernetes --username mk10969 --password {{ lookup('env','GITHUB_ACCESS_TOKEN') }}
      EOC

- name: Deploy argocd-app
  shell: kubectl apply -f /home/{{ K8S.CONFIG.OWNER }}/argocd-app.yaml
