---
- name: Add k8s GPG key
  apt_key:
    url: https://packages.cloud.google.com/apt/doc/apt-key.gpg
    state: present
  become: true

- name: Add k8s apt repository
  apt_repository:
    repo: "deb https://apt.kubernetes.io/ kubernetes-xenial main"
    state: present
    filename: kubernetes
    update_cache: yes
  become: true

- name: Install k8s packages
  apt:
    name: "{{ item }}"
    state: present
    update_cache: yes
  loop:
    - kubelet={{ KUBERNETES.VERSION }}
    - kubeadm={{ KUBERNETES.VERSION }}
    # - kubectl={{ KUBERNETES.VERSION }} # kubeadm installしたら勝手に入る。
  become: true
  notify: require_restart_kubelet

- name: Hold k8s packages
  dpkg_selections:
    name: "{{ item }}"
    selection: hold
  loop:
    - kubelet
    - kubeadm
    - kubectl
  become: true

- name: Check kubelet version
  shell: kubelet --version
  register: check_kubelet_version
  changed_when: false

- name: Debug kubelet version
  debug:
    msg: "{{ check_kubelet_version.stdout }}"

- name: Check kubeadm version
  shell: kubeadm version
  register: check_kubeadm_version
  changed_when: false

- name: Debug kubeadm version
  debug:
    msg: "{{ check_kubeadm_version.stdout }}"
