---
# Prerequisites when Using rook/ceph
- name: device fresh (on kubernetes worker) playbook
  hosts: worker
  roles:
    - dev-fresh
  tasks:
    - name: Remove rook/ceph data
      shell: rm -fr /var/lib/rook
      become: true
