---
- name: k8s cluster setup playbook
  hosts: cluster
  roles:
    - modern-shell
    # install kubeadm, kubectl, kubelet, and docker.
    # configure cgroup, swap, bridge, and lvm.
    - k8s-common
