---
- name: check raw device sda status playbook
  hosts: cluster
  tasks:
    - name: Check lsblk -f
      shell: lsblk -f |grep sda | sed -e 's/ \+/ /g'
      register: result_disk_status
      failed_when: false
      changed_when: false

    - name: Debug raw device; /dev/sda status
      debug:
        msg: "{{ result_disk_status.stdout_lines }}"
      changed_when: false

    - name: Check /dev/mapper/ceph-*
      shell: ls /dev/mapper/ceph-*
      register: result_dev_mapper_ceph_status
      failed_when: false
      changed_when: false

    - name: Debug /dev/mapper/ceph-* status
      debug:
        msg: "{{ result_dev_mapper_ceph_status.stdout_lines }}"
      changed_when: false

    - name: Check /dev/ceph-*
      shell: ls /dev/ceph-*
      register: result_dev_ceph_status
      failed_when: false
      changed_when: false

    - name: Debug /dev/ceph-* status
      debug:
        msg: "{{ result_dev_ceph_status.stdout_lines }}"
      changed_when: false

    - name: Check /var/lib/rook
      shell: ls /var/lib/rook
      register: result_ls
      failed_when: false
      changed_when: false

    - name: Debug /var/lib/rook
      debug:
        msg: "{{ result_ls.stdout_lines }}"
      changed_when: false
