- name: Copy remocon-rs binary file
  copy:
    src: "../files/{{ REMOCON_RS.BINARY }}"
    dest: "{{ REMOCON_RS.DEST }}/remocon-rs"
    owner: root
    group: root
    mode: 0755
  become: true

- name: Create directory {{ GPIO.SCRIPT.DEST }}
  file:
    path: "{{ GPIO.SCRIPT.DEST }}"
    state: directory
    owner: root
    group: root
    mode: 0755
  become: true

- name: Copy irrp.py file
  copy:
    src: "../files/irrp.py"
    dest: "{{ GPIO.SCRIPT.DEST }}/irrp.py"
    owner: root
    group: root
    mode: 0755
  become: true

- name: Copy codes.json file
  copy:
    src: "../files/codes.json"
    dest: "{{ GPIO.SCRIPT.DEST }}/codes.json"
    owner: root
    group: root
    mode: 0755
  become: true

- name: Copy systemd file
  template:
    src: ../templates/remocon-rs.service.j2
    dest: /lib/systemd/system/remocon-rs.service
    owner: root
    group: root
    mode: 0644
  notify: require_remocon_rs_restart
  become: true

- name: Enabled and start remocon-rs service
  systemd:
    name: remocon-rs.service
    enabled: yes
    state: started
    daemon_reload: yes
  become: true
